// ============================================================
//  ARENA CLASH — CONFIG.JS
//  All game data: heroes, maps, chests, leaderboard
// ============================================================

const XP_PER_LEVEL = 500;
const STAT_BONUS_PER_LEVEL = 3;

function getStatBonus(level) {
  return (level - 1) * STAT_BONUS_PER_LEVEL;
}

// ── HEROES ───────────────────────────────────────────────────
const HEROES_DATA = [
  {
    id: "gunman",
    name: "GUN MAN",
    cost: 800,
    rarity: "Rare",
    color: "#F4A261",
    accent: "#E76F51",
    passive: "Adrenaline Rush",
    skill1: "Suppression Fire",
    skill2: "Rapid Reload",
    ultimate: "Bullet Storm",
    ultimateDesc: "Unleashes a barrage of 12 bullets in all directions, each dealing 60% ATK. Lasts 3s.",
    skill1Desc: "Fires 3 rapid shots at the nearest enemy, each hit reduces enemy move speed 30% for 2s.",
    skill2Desc: "Instantly reloads and fires 2 bonus shots with 150% ATK damage.",
    passiveDesc: "When enemies are within 200 units, reload speed doubles and attack speed +40%.",
    stats: { hp: 85, atk: 90, spd: 80, def: 60 },
    unlocked: false,
    level: 1,
    xp: 0,
    lore: "A veteran mercenary whose twin pistols have never missed a payday.",
    description: "Rapid-fire specialist. Adrenaline Rush — reload doubles when enemies are within 200 units.",
    ult_cooldown: 30,
    skill1_cooldown: 8,
    skill2_cooldown: 12,
  },
  {
    id: "archer",
    name: "ARCHER",
    cost: 600,
    rarity: "Uncommon",
    color: "#52B788",
    accent: "#2D6A4F",
    passive: "Archer's Will",
    skill1: "Eagle Eye",
    skill2: "Rain of Arrows",
    ultimate: "Storm Volley",
    ultimateDesc: "Fires 8 homing arrows simultaneously that seek the 3 nearest enemies, each dealing 80% ATK.",
    skill1Desc: "Marks a target for 5s. All attacks against marked target deal +50% dmg and can't miss.",
    skill2Desc: "Launches 5 arrows in a spread fan, hitting all enemies caught in the arc for 70% ATK each.",
    passiveDesc: "Auto-marks an enemy on detection. Next shot after mark = 100% accuracy + 80% ATK bonus.",
    stats: { hp: 70, atk: 95, spd: 75, def: 50 },
    unlocked: false,
    level: 1,
    xp: 0,
    lore: "Once an elven guardian of the ancient forests. Now she fights to reclaim what was stolen.",
    description: "Long-range precision. Archer's Will marks enemies for 3s — next shot hits with 100% accuracy.",
    ult_cooldown: 28,
    skill1_cooldown: 10,
    skill2_cooldown: 14,
  },
  {
    id: "ninja",
    name: "NINJA",
    cost: 1200,
    rarity: "Epic",
    color: "#9B5DE5",
    accent: "#5E2D91",
    passive: "I Am Invisible",
    skill1: "Shadow Step",
    skill2: "Kunai Storm",
    ultimate: "Death Blossom",
    ultimateDesc: "Teleports to each enemy one by one, dealing 200% ATK critical damage. Untargetable during cast.",
    skill1Desc: "Instantly dashes behind the lowest-HP enemy and deals 120% ATK. Resets on kill.",
    skill2Desc: "Throws 5 kunai in a fan pattern. Every 5th kunai in total count still crits for ×2.5.",
    passiveDesc: "On enemy detection, vanishes for 5s. Kunai reload speed +60% while invisible. 25s CD.",
    stats: { hp: 75, atk: 88, spd: 100, def: 55 },
    unlocked: false,
    level: 1,
    xp: 0,
    lore: "No one knows his real name. No one who has seen his face has lived.",
    description: "Shadow assassin. Every 5th kunai crits ×2.5. Vanishes for 5s on enemy detect. 25s CD.",
    ult_cooldown: 35,
    skill1_cooldown: 7,
    skill2_cooldown: 10,
  },
  {
    id: "spearman",
    name: "SPEAR MAN",
    cost: 700,
    rarity: "Uncommon",
    color: "#4CC9F0",
    accent: "#1A78C2",
    passive: "Light as Feather",
    skill1: "Piercing Lance",
    skill2: "Shield Slam",
    ultimate: "Vortex Strike",
    ultimateDesc: "Spins spear in a 180-unit radius, hitting ALL enemies for 150% ATK and stunning for 2s.",
    skill1Desc: "Throws spear in a line piercing all enemies, dealing 110% ATK. Enemies hit are slowed 50%.",
    skill2Desc: "Charges forward with shield, dealing 80% ATK and stunning first enemy hit for 3s.",
    passiveDesc: "Every 5th hit stuns target for 2s. Below 30% HP: attack speed +80%.",
    stats: { hp: 90, atk: 82, spd: 70, def: 85 },
    unlocked: false,
    level: 1,
    xp: 0,
    lore: "A warrior monk who trained 40 years at the Iron Mountains. Truly unbreakable.",
    description: "Every 5th hit stuns. 'Light as Feather' — below 30% HP grants 80% bonus attack speed.",
    ult_cooldown: 32,
    skill1_cooldown: 9,
    skill2_cooldown: 11,
  },
  {
    id: "axeman",
    name: "AXE MAN",
    cost: 900,
    rarity: "Rare",
    color: "#F72585",
    accent: "#7B2D8B",
    passive: "Blood Draw",
    skill1: "Berserker Rage",
    skill2: "Cleave",
    ultimate: "Blood Frenzy",
    ultimateDesc: "Enters a 5s frenzy: attack speed ×3, every hit heals 15% of damage dealt, gains 30% dmg resist.",
    skill1Desc: "Enrages for 4s: +60% ATK, gains lifesteal equal to 25% dmg dealt. Takes 10% more damage.",
    skill2Desc: "Massive cleave hitting all enemies in front for 130% ATK. Heals for 20% of total damage.",
    passiveDesc: "Below 80% HP: every hit heals. Healing scales — lower HP = more healing per strike.",
    stats: { hp: 100, atk: 95, spd: 60, def: 90 },
    unlocked: false,
    level: 1,
    xp: 0,
    lore: "Cursed by a blood witch, he grows stronger with every wound. He stopped fearing death.",
    description: "Blood Draw: below 80% HP every hit heals. Lower HP = more healing per strike.",
    ult_cooldown: 38,
    skill1_cooldown: 12,
    skill2_cooldown: 10,
  },
  {
    id: "starter",
    name: "ROOKIE",
    cost: 0,
    rarity: "Common",
    color: "#ADB5BD",
    accent: "#6C757D",
    passive: "None",
    skill1: "Quick Shot",
    skill2: "Dodge Roll",
    ultimate: "Last Stand",
    ultimateDesc: "Channels for 2s then releases a blast dealing 180% ATK to all enemies. Can't be interrupted.",
    skill1Desc: "Fires a fast shot dealing 90% ATK with no wind-up time. Short 4s cooldown.",
    skill2Desc: "Rolls in joystick direction, gaining 0.5s invincibility and resetting basic attack cooldown.",
    passiveDesc: "No passive. What you see is what you get — pure raw fighting spirit.",
    stats: { hp: 80, atk: 70, spd: 70, def: 70 },
    unlocked: true,
    level: 1,
    xp: 0,
    lore: "Every legend started somewhere. This is where yours begins.",
    description: "Balanced stats, no special passives. Perfect for learning the battlefield.",
    ult_cooldown: 40,
    skill1_cooldown: 4,
    skill2_cooldown: 8,
  },
];

// ── MAPS ─────────────────────────────────────────────────────
const MAPS_DATA = [
  {
    id: "arena",
    name: "Blood Arena",
    desc: "Classic gladiator pit. No mercy, no cover.",
    bgGradient: "linear-gradient(180deg,#1a0505 0%,#2d0a0a 40%,#3d1010 100%)",
    accent: "#F72585",
    gridColor: "rgba(247,37,133,0.022)",
    groundColor: "rgba(247,37,133,0.06)",
    hazards: [],
  },
  {
    id: "ruins",
    name: "Ancient Ruins",
    desc: "Crumbling pillars provide strategic cover. Use the terrain.",
    bgGradient: "linear-gradient(180deg,#0d1a0d 0%,#1a2d1a 40%,#2d3d10 100%)",
    accent: "#52B788",
    gridColor: "rgba(82,183,136,0.022)",
    groundColor: "rgba(82,183,136,0.06)",
    hazards: [],
  },
  {
    id: "volcano",
    name: "Volcano Rift",
    desc: "Lava pits punish those who stand still. Keep moving.",
    bgGradient: "linear-gradient(180deg,#1a0800 0%,#2d1000 40%,#3d1800 100%)",
    accent: "#FF6B35",
    gridColor: "rgba(255,107,53,0.022)",
    groundColor: "rgba(255,107,53,0.06)",
    hazards: [
      { x: 280, y: 180, r: 28, dmg: 4, label: "LAVA" },
      { x: 450, y: 130, r: 22, dmg: 4, label: "LAVA" },
      { x: 360, y: 260, r: 20, dmg: 4, label: "LAVA" },
    ],
  },
  {
    id: "void",
    name: "The Void",
    desc: "Darkness hides ancient horrors. Trust nothing.",
    bgGradient: "linear-gradient(180deg,#050510 0%,#0d0d2e 40%,#050520 100%)",
    accent: "#9B5DE5",
    gridColor: "rgba(155,93,229,0.022)",
    groundColor: "rgba(155,93,229,0.04)",
    hazards: [],
  },
  {
    id: "sky",
    name: "Sky Citadel",
    desc: "Battle above the clouds. One slip — you fall.",
    bgGradient: "linear-gradient(180deg,#061a3d 0%,#0a2a5e 40%,#0d3070 100%)",
    accent: "#4CC9F0",
    gridColor: "rgba(76,201,240,0.022)",
    groundColor: "rgba(76,201,240,0.05)",
    hazards: [],
  },
];

// ── CHESTS ───────────────────────────────────────────────────
const CHESTS_DATA = {
  common: {
    name: "Common Chest",
    cost: 10,
    color: "#8B7355",
    glow: "#c4a97d",
    emoji: "📦",
    drops: [
      { type: "hero",        chance: 0.1,   label: "HERO UNLOCKED!" },
      { type: "levelPoints", chance: 4,     amount: 500,  label: "+500 Level Points" },
      { type: "levelPoints", chance: 10,    amount: 100,  label: "+100 Level Points" },
      { type: "cryan",       chance: 0.001, amount: 50,   label: "+50 Cryan" },
    ],
  },
  uncommon: {
    name: "Uncommon Chest",
    cost: 25,
    color: "#2E7D32",
    glow: "#66BB6A",
    emoji: "🟩",
    drops: [
      { type: "hero",        chance: 1,    label: "HERO UNLOCKED!" },
      { type: "levelPoints", chance: 10,   amount: 500,  label: "+500 Level Points" },
      { type: "levelPoints", chance: 30,   amount: 100,  label: "+100 Level Points" },
      { type: "cryan",       chance: 0.01, amount: 100,  label: "+100 Cryan" },
    ],
  },
  epic: {
    name: "Epic Chest",
    cost: 50,
    color: "#6A1B9A",
    glow: "#CE93D8",
    emoji: "💜",
    drops: [
      { type: "hero",        chance: 10,  label: "HERO UNLOCKED!" },
      { type: "levelPoints", chance: 20,  amount: 1000, label: "+1000 Level Points" },
      { type: "levelPoints", chance: 50,  amount: 100,  label: "+100 Level Points" },
      { type: "cryan",       chance: 0.1, amount: 250,  label: "+250 Cryan" },
    ],
  },
  legend: {
    name: "Legend Chest",
    cost: 100,
    color: "#E65100",
    glow: "#FFB74D",
    emoji: "🔥",
    drops: [
      { type: "hero",        chance: 40,  label: "HERO UNLOCKED!" },
      { type: "levelPoints", chance: 50,  amount: 1000, label: "+1000 Level Points" },
      { type: "levelPoints", chance: 80,  amount: 100,  label: "+100 Level Points" },
      { type: "cryan",       chance: 1,   amount: 500,  label: "+500 Cryan" },
    ],
  },
};

// ── LEADERBOARD ───────────────────────────────────────────────
const LEADERBOARD_DATA = [
  { name: "ShadowBlade_X", hero: "ninja",    wins: 284, kd: "8.2", score: 142000 },
  { name: "ArrowGod99",    hero: "archer",   wins: 241, kd: "6.7", score: 128500 },
  { name: "BerserkerKing", hero: "axeman",   wins: 198, kd: "5.9", score: 112000 },
  { name: "GunSlinger47",  hero: "gunman",   wins: 176, kd: "5.1", score: 98000  },
  { name: "IronSpear",     hero: "spearman", wins: 154, kd: "4.8", score: 87500  },
  { name: "NightCrawler",  hero: "ninja",    wins: 143, kd: "4.2", score: 76000  },
  { name: "DeathMark",     hero: "archer",   wins: 128, kd: "3.9", score: 68000  },
  { name: "StormBreaker",  hero: "axeman",   wins: 112, kd: "3.5", score: 59500  },
  { name: "QuickDraw",     hero: "gunman",   wins: 98,  kd: "3.1", score: 52000  },
];

// ── DAILY QUESTS ──────────────────────────────────────────────
const DAILY_QUESTS = [
  { id: "win3",    desc: "Win 3 matches",           target: 3,  reward: { harwok: 15 },        trackKey: "wins" },
  { id: "kill10",  desc: "Deal 500 total damage",   target: 500,reward: { levelPoints: 200 },   trackKey: "damage" },
  { id: "combo5",  desc: "Hit a 5× combo",          target: 5,  reward: { cryan: 100 },         trackKey: "maxCombo" },
  { id: "play5",   desc: "Play 5 matches",          target: 5,  reward: { harwok: 10 },         trackKey: "matches" },
];

// ── HERO COLOR MAP ────────────────────────────────────────────
const HERO_COLORS = {
  gunman:   "#F4A261",
  archer:   "#52B788",
  ninja:    "#9B5DE5",
  spearman: "#4CC9F0",
  axeman:   "#F72585",
  starter:  "#ADB5BD",
};
